import type { LiteracyStageDefinition, StandardizedLevelDefinition } from './types'

type BaseStandardizedLevelDefinition = Omit<
  StandardizedLevelDefinition,
  'total_questions_per_level' |
  'min_correct_to_pass' |
  'question_difficulty_progression' |
  'question_types_distribution' |
  'reshuffle_enabled'
>

export const STANDARD_QUESTION_DIFFICULTY_PROGRESSION = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const
export const STANDARD_QUESTION_TYPES_DISTRIBUTION = {
  core_skill: 4,
  reinforcement: 3,
  application: 2,
  challenge: 1,
} as const

export const literacyStageDefinitions: LiteracyStageDefinition[] = [
  {
    id: 'pre_literacy_early_exposure',
    display_name: 'Pre-Literacy / Early Exposure',
    level_range: { start: 1, end: 4 },
    summary: 'Icon-based and picture-supported language exposure with no full sentence requirement.',
    instructional_focus: [
      'Word recognition through icons and pictures',
      'Basic noun and action awareness',
      'Single-word selection and matching',
    ],
    cognitive_load_notes: [
      'Single-step interactions only',
      'Minimal text decoding demand',
    ],
  },
  {
    id: 'early_sentence_awareness',
    display_name: 'Early Sentence Awareness',
    level_range: { start: 5, end: 8 },
    summary: '2-3 word sentence awareness with simple subject-verb patterns and small word banks.',
    instructional_focus: [
      '2-3 word sentence building',
      'Noun and verb identification',
      'Simple present tense only',
    ],
    cognitive_load_notes: [
      'Short sentences only',
      'Limited vocabulary options and high scaffolding',
    ],
  },
  {
    id: 'emerging_reader',
    display_name: 'Emerging Reader',
    level_range: { start: 9, end: 12 },
    summary: '4-6 word sentence control with articles, adjectives, agreement, and basic logic checks.',
    instructional_focus: [
      'Subject-verb agreement',
      'Articles a/an/the',
      'Simple adjectives and logical consistency',
    ],
    cognitive_load_notes: [
      'Moderate word bank expansion',
      'Multi-part sentence checks with support',
    ],
  },
  {
    id: 'developing_fluency',
    display_name: 'Developing Fluency',
    level_range: { start: 13, end: 16 },
    summary: 'Compound structures with and, pronouns, past tense introduction, and short multi-sentence output.',
    instructional_focus: [
      'Compound sentences with and',
      'Pronouns and past tense introduction',
      '2-3 sentence paragraph building',
    ],
    cognitive_load_notes: [
      'Multi-step construction',
      'Reduced scaffolding with guided supports',
    ],
  },
  {
    id: 'third_grade_mastery',
    display_name: 'Third Grade Mastery',
    level_range: { start: 17, end: 20 },
    summary: 'Paragraph-level construction, sequencing, varied sentences, and multi-error detection with minimal scaffolding.',
    instructional_focus: [
      'Complete paragraphs with beginning-middle-end',
      'Sentence variation and sequencing',
      'Independent construction and multi-error analysis',
    ],
    cognitive_load_notes: [
      'Higher language complexity within end-of-third-grade bounds',
      'Minimal scaffolds and stronger accuracy expectations',
    ],
  },
]

const base20LevelFramework: BaseStandardizedLevelDefinition[] = [
  {
    level_number: 1,
    literacy_stage: 'pre_literacy_early_exposure',
    max_sentence_length: 1,
    grammar_targets: ['icon-to-word recognition', 'basic noun awareness'],
    vocabulary_size: 4,
    allowed_sentence_types: ['single_word'],
    error_types_included: ['noun_identification'],
    scaffolding_level: 'maximum_visual',
    required_accuracy_to_pass: 0.8,
    repetition_requirement: { minimum_attempts: 3, consecutive_successes_required: 2, consistency_window: 3 },
  },
  {
    level_number: 2,
    literacy_stage: 'pre_literacy_early_exposure',
    max_sentence_length: 1,
    grammar_targets: ['icon-to-word recognition', 'basic verb awareness'],
    vocabulary_size: 5,
    allowed_sentence_types: ['single_word'],
    error_types_included: ['noun_identification', 'verb_identification'],
    scaffolding_level: 'maximum_visual',
    required_accuracy_to_pass: 0.8,
    repetition_requirement: { minimum_attempts: 3, consecutive_successes_required: 2, consistency_window: 3 },
  },
  {
    level_number: 3,
    literacy_stage: 'pre_literacy_early_exposure',
    max_sentence_length: 2,
    grammar_targets: ['noun sorting', 'action word sorting'],
    vocabulary_size: 6,
    allowed_sentence_types: ['single_word', 'word_pair'],
    error_types_included: ['noun_identification', 'verb_identification'],
    scaffolding_level: 'maximum_visual',
    required_accuracy_to_pass: 0.82,
    repetition_requirement: { minimum_attempts: 4, consecutive_successes_required: 2, consistency_window: 4 },
  },
  {
    level_number: 4,
    literacy_stage: 'pre_literacy_early_exposure',
    max_sentence_length: 2,
    grammar_targets: ['single-word drag and drop', 'noun-verb pairing awareness'],
    vocabulary_size: 8,
    allowed_sentence_types: ['single_word', 'word_pair'],
    error_types_included: ['noun_identification', 'verb_identification', 'logic_mismatch'],
    scaffolding_level: 'high',
    required_accuracy_to_pass: 0.82,
    repetition_requirement: { minimum_attempts: 4, consecutive_successes_required: 2, consistency_window: 4 },
  },
  {
    level_number: 5,
    literacy_stage: 'early_sentence_awareness',
    max_sentence_length: 3,
    grammar_targets: ['subject + verb', 'simple present tense'],
    vocabulary_size: 8,
    allowed_sentence_types: ['simple_sv'],
    error_types_included: ['missing_component', 'word_order', 'verb_identification'],
    scaffolding_level: 'high',
    required_accuracy_to_pass: 0.83,
    repetition_requirement: { minimum_attempts: 4, consecutive_successes_required: 2, consistency_window: 4 },
  },
  {
    level_number: 6,
    literacy_stage: 'early_sentence_awareness',
    max_sentence_length: 3,
    grammar_targets: ['subject + verb', 'noun/verb identification'],
    vocabulary_size: 10,
    allowed_sentence_types: ['simple_sv'],
    error_types_included: ['missing_component', 'word_order', 'noun_identification', 'verb_identification'],
    scaffolding_level: 'high',
    required_accuracy_to_pass: 0.84,
    repetition_requirement: { minimum_attempts: 4, consecutive_successes_required: 2, consistency_window: 4 },
  },
  {
    level_number: 7,
    literacy_stage: 'early_sentence_awareness',
    max_sentence_length: 4,
    grammar_targets: ['subject + verb + object', 'simple present tense'],
    vocabulary_size: 12,
    allowed_sentence_types: ['simple_sv', 'simple_svo'],
    error_types_included: ['missing_component', 'word_order', 'logic_mismatch'],
    scaffolding_level: 'high',
    required_accuracy_to_pass: 0.84,
    repetition_requirement: { minimum_attempts: 5, consecutive_successes_required: 2, consistency_window: 4 },
  },
  {
    level_number: 8,
    literacy_stage: 'early_sentence_awareness',
    max_sentence_length: 4,
    grammar_targets: ['simple present tense', 'noun and verb role recognition'],
    vocabulary_size: 14,
    allowed_sentence_types: ['simple_sv', 'simple_svo'],
    error_types_included: ['missing_component', 'word_order', 'noun_identification', 'verb_identification', 'logic_mismatch'],
    scaffolding_level: 'guided',
    required_accuracy_to_pass: 0.85,
    repetition_requirement: { minimum_attempts: 5, consecutive_successes_required: 2, consistency_window: 5 },
  },
  {
    level_number: 9,
    literacy_stage: 'emerging_reader',
    max_sentence_length: 5,
    grammar_targets: ['subject-verb agreement', 'article usage'],
    vocabulary_size: 16,
    allowed_sentence_types: ['simple_sv', 'simple_svo'],
    error_types_included: ['missing_component', 'word_order', 'subject_verb_agreement', 'article_usage'],
    scaffolding_level: 'guided',
    required_accuracy_to_pass: 0.85,
    repetition_requirement: { minimum_attempts: 5, consecutive_successes_required: 2, consistency_window: 5 },
  },
  {
    level_number: 10,
    literacy_stage: 'emerging_reader',
    max_sentence_length: 5,
    grammar_targets: ['subject-verb agreement', 'a/an/the'],
    vocabulary_size: 18,
    allowed_sentence_types: ['simple_sv', 'simple_svo', 'linking_sentence'],
    error_types_included: ['word_order', 'subject_verb_agreement', 'article_usage', 'logic_mismatch'],
    scaffolding_level: 'guided',
    required_accuracy_to_pass: 0.86,
    repetition_requirement: { minimum_attempts: 5, consecutive_successes_required: 2, consistency_window: 5 },
  },
  {
    level_number: 11,
    literacy_stage: 'emerging_reader',
    max_sentence_length: 6,
    grammar_targets: ['simple adjectives', 'subject-verb agreement', 'articles'],
    vocabulary_size: 20,
    allowed_sentence_types: ['simple_svo', 'linking_sentence'],
    error_types_included: ['word_order', 'subject_verb_agreement', 'article_usage', 'logic_mismatch'],
    scaffolding_level: 'guided',
    required_accuracy_to_pass: 0.86,
    repetition_requirement: { minimum_attempts: 6, consecutive_successes_required: 2, consistency_window: 5 },
  },
  {
    level_number: 12,
    literacy_stage: 'emerging_reader',
    max_sentence_length: 6,
    grammar_targets: ['sentence completeness', 'basic logical consistency', 'agreement review'],
    vocabulary_size: 22,
    allowed_sentence_types: ['simple_svo', 'linking_sentence'],
    error_types_included: ['missing_component', 'word_order', 'subject_verb_agreement', 'article_usage', 'logic_mismatch'],
    scaffolding_level: 'moderate',
    required_accuracy_to_pass: 0.87,
    repetition_requirement: { minimum_attempts: 6, consecutive_successes_required: 2, consistency_window: 6 },
  },
  {
    level_number: 13,
    literacy_stage: 'developing_fluency',
    max_sentence_length: 8,
    grammar_targets: ['compound sentence with and', 'pronouns introduction'],
    vocabulary_size: 24,
    allowed_sentence_types: ['simple_svo', 'compound_with_and'],
    error_types_included: ['word_order', 'subject_verb_agreement', 'pronoun_reference', 'conjunction_usage'],
    scaffolding_level: 'moderate',
    required_accuracy_to_pass: 0.87,
    repetition_requirement: { minimum_attempts: 6, consecutive_successes_required: 2, consistency_window: 6 },
  },
  {
    level_number: 14,
    literacy_stage: 'developing_fluency',
    max_sentence_length: 8,
    grammar_targets: ['pronouns', 'past tense introduction', 'and conjunction'],
    vocabulary_size: 26,
    allowed_sentence_types: ['simple_svo', 'compound_with_and'],
    error_types_included: ['subject_verb_agreement', 'pronoun_reference', 'tense_consistency', 'conjunction_usage'],
    scaffolding_level: 'moderate',
    required_accuracy_to_pass: 0.88,
    repetition_requirement: { minimum_attempts: 6, consecutive_successes_required: 2, consistency_window: 6 },
  },
  {
    level_number: 15,
    literacy_stage: 'developing_fluency',
    max_sentence_length: 10,
    grammar_targets: ['multi-step sentence building', 'past tense practice', 'logical sequencing'],
    vocabulary_size: 28,
    allowed_sentence_types: ['compound_with_and', 'short_paragraph'],
    error_types_included: ['word_order', 'subject_verb_agreement', 'tense_consistency', 'logic_mismatch', 'conjunction_usage'],
    scaffolding_level: 'light',
    required_accuracy_to_pass: 0.88,
    repetition_requirement: { minimum_attempts: 7, consecutive_successes_required: 2, consistency_window: 6 },
  },
  {
    level_number: 16,
    literacy_stage: 'developing_fluency',
    max_sentence_length: 14,
    grammar_targets: ['2-3 sentence paragraph construction', 'pronouns', 'basic conjunctions'],
    vocabulary_size: 30,
    allowed_sentence_types: ['compound_with_and', 'short_paragraph'],
    error_types_included: ['subject_verb_agreement', 'pronoun_reference', 'tense_consistency', 'conjunction_usage', 'paragraph_sequence'],
    scaffolding_level: 'light',
    required_accuracy_to_pass: 0.89,
    repetition_requirement: { minimum_attempts: 7, consecutive_successes_required: 2, consistency_window: 6 },
  },
  {
    level_number: 17,
    literacy_stage: 'third_grade_mastery',
    max_sentence_length: 16,
    grammar_targets: ['paragraph sequencing', 'sentence variation', 'agreement reinforcement'],
    vocabulary_size: 32,
    allowed_sentence_types: ['short_paragraph', 'multi_sentence_paragraph'],
    error_types_included: ['subject_verb_agreement', 'tense_consistency', 'conjunction_usage', 'paragraph_sequence'],
    scaffolding_level: 'light',
    required_accuracy_to_pass: 0.89,
    repetition_requirement: {
      minimum_attempts: 7,
      consecutive_successes_required: 2,
      consistency_window: 7,
      fluency_gate: { max_seconds: 150, min_accuracy: 0.85 },
    },
  },
  {
    level_number: 18,
    literacy_stage: 'third_grade_mastery',
    max_sentence_length: 18,
    grammar_targets: ['beginning-middle-end story structure', 'error detection across sentence types'],
    vocabulary_size: 34,
    allowed_sentence_types: ['multi_sentence_paragraph'],
    error_types_included: ['subject_verb_agreement', 'tense_consistency', 'conjunction_usage', 'paragraph_sequence', 'logic_mismatch'],
    scaffolding_level: 'minimal',
    required_accuracy_to_pass: 0.9,
    repetition_requirement: {
      minimum_attempts: 8,
      consecutive_successes_required: 2,
      consistency_window: 7,
      fluency_gate: { max_seconds: 140, min_accuracy: 0.86 },
    },
  },
  {
    level_number: 19,
    literacy_stage: 'third_grade_mastery',
    max_sentence_length: 20,
    grammar_targets: ['independent construction', 'multi-error detection', 'expanded vocabulary usage'],
    vocabulary_size: 36,
    allowed_sentence_types: ['multi_sentence_paragraph', 'independent_composition'],
    error_types_included: ['subject_verb_agreement', 'article_usage', 'pronoun_reference', 'tense_consistency', 'paragraph_sequence', 'multi_error_detection'],
    scaffolding_level: 'minimal',
    required_accuracy_to_pass: 0.9,
    repetition_requirement: {
      minimum_attempts: 8,
      consecutive_successes_required: 3,
      consistency_window: 8,
      fluency_gate: { max_seconds: 130, min_accuracy: 0.87 },
    },
  },
  {
    level_number: 20,
    literacy_stage: 'third_grade_mastery',
    max_sentence_length: 24,
    grammar_targets: ['complete paragraph composition', 'logical sequencing', 'sentence variation', 'independent proofreading'],
    vocabulary_size: 40,
    allowed_sentence_types: ['multi_sentence_paragraph', 'independent_composition'],
    error_types_included: ['subject_verb_agreement', 'article_usage', 'pronoun_reference', 'tense_consistency', 'conjunction_usage', 'paragraph_sequence', 'multi_error_detection'],
    scaffolding_level: 'minimal',
    required_accuracy_to_pass: 0.92,
    repetition_requirement: {
      minimum_attempts: 8,
      consecutive_successes_required: 3,
      consistency_window: 8,
      fluency_gate: { max_seconds: 120, min_accuracy: 0.88 },
    },
  },
]

export const standardized20LevelFramework: StandardizedLevelDefinition[] = base20LevelFramework.map((level) => ({
  ...level,
  total_questions_per_level: 10,
  min_correct_to_pass: 8,
  question_difficulty_progression: [...STANDARD_QUESTION_DIFFICULTY_PROGRESSION] as [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  question_types_distribution: { ...STANDARD_QUESTION_TYPES_DISTRIBUTION },
  reshuffle_enabled: true,
}))

export function getStandardizedLevel(levelNumber: number): StandardizedLevelDefinition {
  const found = standardized20LevelFramework.find((level) => level.level_number === levelNumber)
  if (!found) {
    throw new Error(`Invalid curriculum level: ${levelNumber}. Expected 1-20.`)
  }
  return found
}
